### ISSUE TITLE
To-do list before ready

### ISSUE THREAD

**Issue by jbradt** [ATTPC/attpc-daq#1]
These things need to be done before the system can be ready for use in some form:

- [x] Provide a way to update the config list
- [ ] Add interface for adding new experiments
- [ ] Make sure runs, configs, etc are separated by experiment name somehow
- [ ] Create a button to dump run data to a file
- [ ] Fix run start time and duration fields on status page
- [x] Test file renaming function
- [ ] Embed fonts
- [ ] Add a run type field (production, testing, etc.)
- [x] Fix version of Zeep library in `requirements.py`
- [ ] Improve visual rendering of forms
- [x] Fix timezones
- [x] Fix redirects in CRUD views
- [ ] Make sure login_required is everywhere it is needed

**Comment by jbradt** [comment]
Made individual issues.
